# fish completion for cssgrep. Keep in sync with the USAGE string in index.js.
# Install: place this file in ~/.config/fish/completions/ (named cssgrep.fish).

complete -c cssgrep -s r -l recursive -d 'Recurse into directory arguments'
complete -c cssgrep -l ext -x -d 'Extensions to scan with -r (comma-separated)'
complete -c cssgrep -s i -l ignore -x -d 'Skip files/dirs matching glob while recursing'
complete -c cssgrep -l ignore-file -r -F -d 'Read ignore globs from a file'
complete -c cssgrep -s n -l line-number -d 'Prefix each match with line:col'
complete -c cssgrep -s p -l print -d 'Pretty-print the matched node HTML'
complete -c cssgrep -l attr -x -d 'Print the value of an attribute'
complete -c cssgrep -l text -d 'Print the matched node text content'
complete -c cssgrep -l json -d 'Print one JSON object per match (NDJSON)'
complete -c cssgrep -l parent -x -d 'Report the n-th ancestor of each match'
complete -c cssgrep -s w -l max-width -x -d 'Truncate shown line to n columns'
complete -c cssgrep -s A -l after-context -x -d 'Print n lines after each match'
complete -c cssgrep -s B -l before-context -x -d 'Print n lines before each match'
complete -c cssgrep -s C -l context -x -d 'Print n lines around each match'
complete -c cssgrep -s m -l max-count -x -d 'Stop after n matches per file'
complete -c cssgrep -s M -l max-total -x -d 'Stop after n matches in total'
complete -c cssgrep -s c -l count -d 'Print only a count of matches'
complete -c cssgrep -s l -l files-with-matches -d 'Print only names of files with a match'
complete -c cssgrep -s L -l files-without-match -d 'Print only names of files without a match'
complete -c cssgrep -s q -l quiet -d 'Print nothing; exit on first match'
complete -c cssgrep -s 0 -l null -d 'Separate the file name with a NUL byte'
complete -c cssgrep -s H -l with-filename -d 'Always print the file name prefix'
complete -c cssgrep -l no-filename -d 'Never print the file name prefix'
complete -c cssgrep -l color -x -a 'auto always never' -d 'Colorize output'
complete -c cssgrep -s h -l help -d 'Show help and exit'
complete -c cssgrep -s V -l version -d 'Show version and exit'
